export default {
  title: 'Plan de salle',
  subtitleDay: 'Vue journaliere de l\'occupation de la salle',
  subtitleWeek: 'Vue hebdomadaire de l\'occupation de la salle',

  // Slot form
  hall: 'Salle',
  team: 'Equipe',
  dayOfWeek: 'Jour de la semaine',
  slotType: 'Type',
  startTime: 'Heure de debut',
  endTime: 'Heure de fin',
  recurring: 'Recurrent',
  validFrom: 'Valable du',
  validTo: 'Valable au',
  indefinitely: 'Indefiniment',
  label: 'Libelle',
  notes: 'Notes',

  // Slot types
  typeTraining: 'Entrainement',
  typeGame: 'Match',
  typeEvent: 'Evenement',
  typeOther: 'Autre',

  // Day names (full)
  dayMonday: 'Lundi',
  dayTuesday: 'Mardi',
  dayWednesday: 'Mercredi',
  dayThursday: 'Jeudi',
  dayFriday: 'Vendredi',
  daySaturday: 'Samedi',
  daySunday: 'Dimanche',

  // Slot editor
  editSlot: 'Modifier le creneau',
  editSlotTitle: 'Modifier le creneau',
  newSlotTitle: 'Nouveau creneau',
  deleteSlotConfirm: 'Voulez-vous vraiment supprimer ce creneau ?',
  selectPlaceholder: '-- Selectionner --',

  // Validation
  hallRequired: 'Veuillez selectionner une salle',
  dayRequired: 'Veuillez selectionner un jour',
  startTimeRequired: 'L\'heure de debut est requise',
  endTimeRequired: 'L\'heure de fin est requise',

  // Closure manager
  closuresTitle: 'Gerer les fermetures de salle',
  currentClosures: 'Fermetures en cours',
  addNewClosure: 'Ajouter une fermeture',
  editClosure: 'Modifier la fermeture',
  noClosures: 'Aucune fermeture en cours',
  deleteClosureConfirm: 'Voulez-vous vraiment supprimer cette fermeture de salle ?',

  // Closure sources
  source: 'Source',
  sourceCaretaker: 'Concierge',
  sourceAdmin: 'Admin',
  sourceAutomatic: 'Automatique',
  sourceGcal: 'Google Calendar',
  sourceSchoolHolidays: 'Vacances scolaires',
  closed: 'Ferme',
  allHalls: 'Toutes les salles',
  halls: 'salles',
  editAppliesToAllHalls: 'La modification s\'applique a {{count}} salles',

  // Navigation
  today: 'Aujourd\'hui',
  closures: 'Fermetures',
  prevWeek: 'Semaine precedente',
  nextWeek: 'Semaine suivante',

  // Summary
  summary: 'Resume',

  // Virtual slots
  typeAway: 'Exterieur',
  autoGenerated: 'Genere automatiquement',
  cancelled: 'Annule',

  // Virtual slot detail labels
  league: 'Ligue',
  start: 'Debut',
  slot: 'Creneau',
  result: 'Resultat',
  location: 'Lieu',
  allDay: 'Toute la journee',
  date: 'Date',
  reason: 'Motif',

  // Game statuses
  statusScheduled: 'Planifie',
  statusLive: 'En direct',
  statusCompleted: 'Termine',
  statusPostponed: 'Reporte',

  // Claim system
  slotFreed: 'Disponible',
  slotClaimed: 'Reclame',
  claimSlotTitle: 'Reclamer du temps de salle',
  claimConfirm: 'Reclamer',
  claimRelease: 'Liberer',
  claimReleaseConfirm: 'Voulez-vous vraiment liberer cette reclamation ?',
  claimAlreadyTaken: 'Ce creneau a deja ete reclame.',
  claimPastDate: 'Les creneaux passes ne peuvent pas etre reclames.',
  claimTeamLabel: 'Pour l\'equipe',
  claimReasonCancelled: 'Entrainement annule',
  claimReasonAway: 'Match a l\'exterieur',
  claimReasonSpielhalle: 'Spielhalle',
  claimOriginalTeam: 'A l\'origine',
  claimClaimedBy: 'Reclame par',
  claimClaimedAt: 'Reclame le',
  claimNotes: 'Notes',
  claimSuccess: 'Creneau reclame avec succes !',
  claimReleased: 'Reclamation liberee.',
  claimDetailTitle: 'Details de la reclamation',

  // Filter
  vbOnly: 'VB uniquement',
  all: 'Tout',

  // Admin navigation
  updateFutureTrainings: 'Mettre a jour les entrainements futurs',
  goToTrainings: 'Aller aux entrainements',
  goToGames: 'Aller aux matchs',

  // Available slots
  slotsAvailable: '{{count}} creneau(x) disponible(s)',
  slotsAvailableTitle: 'Creneaux disponibles',
  slotsAvailableNone: 'Aucun creneau disponible',
} as const
