import { useTranslation } from 'react-i18next'
import Modal from '../../../components/Modal'
import TeamChip from '../../../components/TeamChip'
import type { HallSlot, Hall, Team, Game, Training, HallEvent } from '../../../types'

interface Props {
  slot: HallSlot
  halls: Hall[]
  teams: Team[]
  onClose: () => void
}

function DetailRow({ label, value }: { label: string; value: string }) {
  if (!value) return null
  return (
    <div className="flex gap-3 py-1.5">
      <span className="w-24 shrink-0 text-sm font-medium text-gray-500 dark:text-gray-400">{label}</span>
      <span className="text-sm text-gray-900 dark:text-gray-100">{value}</span>
    </div>
  )
}

export default function VirtualSlotDetailModal({ slot, halls, teams, onClose }: Props) {
  const { t } = useTranslation('hallenplan')
  const meta = slot._virtual!

  const hallName = halls.find((h) => h.id === slot.hall)?.name ?? ''
  const teamObj = teams.find((tm) => tm.id === slot.team)
  const teamName = teamObj?.name ?? ''

  function renderGame() {
    const game = meta.sourceRecord as Game
    const statusLabels: Record<string, string> = {
      scheduled: 'Geplant',
      live: 'Live',
      completed: 'Abgeschlossen',
      postponed: 'Verschoben',
    }

    return (
      <div className="space-y-1">
        <DetailRow label={t('hall')} value={hallName} />
        {teamName && (
          <div className="flex gap-3 py-1.5">
            <span className="w-24 shrink-0 text-sm font-medium text-gray-500 dark:text-gray-400">{t('team')}</span>
            <TeamChip team={teamName} size="sm" />
          </div>
        )}
        <DetailRow label="Liga" value={game.league} />
        <DetailRow label="Start" value={game.time?.slice(0, 5) || ''} />
        <DetailRow label="Slot" value={`${slot.start_time}–${slot.end_time}`} />
        <DetailRow label="Status" value={statusLabels[game.status] || game.status} />
        {game.status === 'completed' && (
          <DetailRow label="Ergebnis" value={`${game.home_score}:${game.away_score}`} />
        )}
        {meta.isAway && (
          <div className="mt-3 rounded-lg bg-amber-50 px-3 py-2 text-sm text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">
            {t('typeAway')} — {game.home_team} vs {game.away_team}
          </div>
        )}
      </div>
    )
  }

  function renderTraining() {
    const training = meta.sourceRecord as Training

    return (
      <div className="space-y-1">
        <DetailRow label={t('hall')} value={hallName} />
        {teamName && (
          <div className="flex gap-3 py-1.5">
            <span className="w-24 shrink-0 text-sm font-medium text-gray-500 dark:text-gray-400">{t('team')}</span>
            <TeamChip team={teamName} size="sm" />
          </div>
        )}
        <DetailRow label={t('startTime')} value={slot.start_time} />
        <DetailRow label={t('endTime')} value={slot.end_time} />
        <DetailRow label={t('notes')} value={training.notes} />
        {meta.isCancelled && (
          <div className="mt-3 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-800 dark:bg-red-900/30 dark:text-red-300">
            {t('cancelled')}{training.cancel_reason ? `: ${training.cancel_reason}` : ''}
          </div>
        )}
      </div>
    )
  }

  function renderHallEvent() {
    const event = meta.sourceRecord as HallEvent

    return (
      <div className="space-y-1">
        <DetailRow label={t('hall')} value={hallName} />
        <DetailRow label={t('label')} value={event.title} />
        <DetailRow label={t('startTime')} value={event.start_time?.slice(0, 5) || 'Ganztägig'} />
        <DetailRow label={t('endTime')} value={event.end_time?.slice(0, 5) || ''} />
        <DetailRow label="Ort" value={event.location} />
      </div>
    )
  }

  const titles: Record<string, string> = {
    game: meta.isAway ? t('typeAway') : t('typeGame'),
    training: t('typeTraining'),
    hall_event: t('typeEvent'),
  }

  const title = meta.source === 'game'
    ? `${titles.game}: ${(meta.sourceRecord as Game).home_team} vs ${(meta.sourceRecord as Game).away_team}`
    : meta.source === 'training'
      ? `${titles.training}${teamName ? ` — ${teamName}` : ''}`
      : (meta.sourceRecord as HallEvent).title

  return (
    <Modal open onClose={onClose} title={title} size="sm">
      {meta.source === 'game' && renderGame()}
      {meta.source === 'training' && renderTraining()}
      {meta.source === 'hall_event' && renderHallEvent()}

      <div className="mt-4 border-t border-gray-200 pt-3 text-center dark:border-gray-700">
        <span className="text-xs text-gray-400 dark:text-gray-500">{t('autoGenerated')}</span>
      </div>
    </Modal>
  )
}
