export default {
  title: 'Halleplan',
  subtitleDay: 'Tagesaasicht vo de Hallebelegig',
  subtitleWeek: 'Wuchenaasicht vo de Hallebelegig',

  // Slot form
  hall: 'Halle',
  team: 'Team',
  dayOfWeek: 'Wuchetag',
  slotType: 'Typ',
  startTime: 'Startzit',
  endTime: 'Ändzit',
  recurring: 'Wiederkehrend',
  validFrom: 'Gültig ab',
  validTo: 'Gültig bis',
  indefinitely: 'Unbefristet',
  label: 'Bezeichnig',
  notes: 'Notize',

  // Slot types
  typeTraining: 'Training',
  typeGame: 'Spiel',
  typeEvent: 'Event',
  typeOther: 'Anderi',

  // Day names (full)
  dayMonday: 'Mäntig',
  dayTuesday: 'Ziischtig',
  dayWednesday: 'Mittwuch',
  dayThursday: 'Dunschtig',
  dayFriday: 'Friitig',
  daySaturday: 'Samschtig',
  daySunday: 'Sunntig',

  // Slot editor
  editSlot: 'Slot bearbeite',
  editSlotTitle: 'Slot bearbeite',
  newSlotTitle: 'Neue Slot',
  deleteSlotConfirm: 'Bisch sicher, dass du de Slot lösche wotsch?',
  selectPlaceholder: '-- Uswähle --',

  // Validation
  hallRequired: 'Bitte wähl e Halle',
  dayRequired: 'Bitte wähl en Tag',
  startTimeRequired: 'Startzit bruuchts',
  endTimeRequired: 'Ändzit bruuchts',

  // Closure manager
  closuresTitle: 'Hallesperrige verwalte',
  currentClosures: 'Aktuelli Sperrige',
  addNewClosure: 'Neui Sperrig',
  editClosure: 'Sperrig bearbeite',
  noClosures: 'Käni aktive Sperrige',
  deleteClosureConfirm: 'Bisch sicher, dass du die Hallesperrig lösche wotsch?',

  // Closure sources
  source: 'Quelle',
  sourceCaretaker: 'Huuswart',
  sourceAdmin: 'Admin',
  sourceAutomatic: 'Automatisch',
  sourceGcal: 'Google Kaländer',
  sourceSchoolHolidays: 'Schuelferie',
  closed: 'Gsperrt',
  allHalls: 'Alli Halle',
  halls: 'Halle',
  editAppliesToAllHalls: 'Änderig gilt für {{count}} Halle',

  // Navigation
  today: 'Hüt',
  closures: 'Sperrige',
  prevWeek: 'Vorhärigi Wuche',
  nextWeek: 'Nöchscht Wuche',

  // Summary
  summary: 'Übersicht',

  // Virtual slots
  typeAway: 'Uswärts',
  autoGenerated: 'Automatisch generiert',
  cancelled: 'Abgseit',

  // Virtual slot detail labels
  league: 'Liga',
  start: 'Start',
  slot: 'Slot',
  result: 'Ergebnis',
  location: 'Ort',
  allDay: 'De ganz Tag',
  date: 'Datum',
  reason: 'Grund',

  // Game statuses
  statusScheduled: 'Geplant',
  statusLive: 'Live',
  statusCompleted: 'Abgschlosse',
  statusPostponed: 'Verschobe',

  // Claim system
  slotFreed: 'Frei',
  slotClaimed: 'Beansprucht',
  claimSlotTitle: 'Hallezit beanspruche',
  claimConfirm: 'Beanspruche',
  claimRelease: 'Freigäh',
  claimReleaseConfirm: 'Bisch sicher, dass du die Beanspruchig ufhebe wotsch?',
  claimAlreadyTaken: 'De Slot isch scho beansprucht worde.',
  claimPastDate: 'Vergangeni Slots chönd nöd beansprucht werde.',
  claimTeamLabel: 'Für Team',
  claimReasonCancelled: 'Training abgseit',
  claimReasonAway: 'Uswärtsspiel',
  claimReasonSpielhalle: 'Spielhalle',
  claimOriginalTeam: 'Ursprünglich',
  claimClaimedBy: 'Beansprucht vo',
  claimClaimedAt: 'Beansprucht am',
  claimNotes: 'Notize',
  claimSuccess: 'Slot erfolgriich beansprucht!',
  claimReleased: 'Beanspruchig ufghobe.',
  claimDetailTitle: 'Beanspruchig Details',

  // Filter
  vbOnly: 'Nur VB',
  all: 'Alli',

  // Admin navigation
  updateFutureTrainings: 'Zukünftigi Trainings aktualisiere',
  goToTrainings: 'Zu Trainings',
  goToGames: 'Zu Spiel',

  // Available slots
  slotsAvailable: '{{count}} Halle frei',
  slotsAvailableTitle: 'Freii Halle',
  slotsAvailableNone: 'Käni freie Halle',
} as const
